export const ADD_REDIS_CLIENT = "ADD_REDIS_CLIENT";
export const REMOVE_REDIS_ClIENT = "REMOVE_REDIS_ClIENT";
export const CONNECT_REDIS = "CONNECT_REDIS";
export const DISCONNECT_REDIS = "DISCONNECT_REDIS";
export const SET_SELECTED_CLIENT_INDEX = "SET_SELECTED_CLIENT_INDEX";
